In [1]:
import glob
from dalab import read_pickle
import pandas as pd
import numpy as np
from langdetect import detect
from collections import Counter
from nltk import word_tokenize

import pandas as pd
import numpy as np
from nltk.tokenize import word_tokenize
import spacy
from time import time
from keras.preprocessing.text import one_hot
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
from keras.layers import Embedding, Dense, Conv1D, MaxPooling1D, Flatten, Dropout, SimpleRNN, GRU, LSTM
from keras.layers import Input, Dense
from keras.models import Model
from keras.models import Sequential
from matplotlib import pyplot as plt

%matplotlib inline

Using TensorFlow backend.

In [2]:
df = pd.read_pickle('data/medium_stories/dataframes/en_lower_stories.pickle').reset_index(drop=True)
df = df.sample(frac=1)
df = df.drop_duplicates(subset='story')
df.head()

,class,story
1791,computer_vision,"every year, traffic accidents account for 2.2..."
11943,web_scraping,"we all scrape web data. well, those of us who..."
8378,artificial_intelligence,we hear about impressive achievements related...
12461,genetic_programming,a computer deals with 3 things: a) data b) al...
11628,nlp,lately i’ve been delving into the world of ag...

In [3]:
for topic in df['class'].unique():
    print(topic, len(df[df['class'] == topic]))

computer_vision 793
web_scraping 477
artificial_intelligence 664
genetic_programming 61
nlp 684
web_crawling 142
transfer_learning 499
data_engineering 403
data_extraction 351
ai 817
data_science 818
deep_learning 763
web_scrape 182
time_series 766
big_data 530
machine_learning 826
web_crawler 228
pattern_recognition 71
natural_language_processing 571
machine_translation 270
_speech_recognition 483
data_mining 464
intelligent_machine 221
genetic_algorithm 227
recurrent_neural 370
reinforcement_learning 167
object_recognition 105
convolution_neural 191
neural_network 220
image_understanding 119
evolutionary_computation 17
speech_processing 9

In [4]:
MAXLEN = 1000
VOCAB_SIZE = 20000
TRAIN_SIZE = 10000

In [5]:
nlp = spacy.load('en_core_web_sm')

In [6]:
all_words = word_tokenize(' '.join(df.story.tolist()))
word_counts = Counter(all_words).most_common(VOCAB_SIZE)
words = [w[0] for w in word_counts]

In [7]:
embed_dic = {}
for index, word in enumerate(words):
    if index % 500 == 0: print(index)
    token = nlp(word)
    embed_dic[token.text] = token.vector

0
500
1000
1500
2000
2500
3000
3500
4000
4500
5000
5500
6000
6500
7000
7500
8000
8500
9000
9500
10000
10500
11000
11500
12000
12500
13000
13500
14000
14500
15000
15500
16000
16500
17000
17500
18000
18500
19000
19500

In [8]:
embed_words = pd.DataFrame(embed_dic).T
embed_words.head(10)

,0,1,2,3,4,5,6,7,8,9,...,374,375,376,377,378,379,380,381,382,383
!,0.671140,-0.475781,1.225882,-0.533356,1.413614,2.528172,-0.030113,0.486537,3.412096,1.299003,...,0.361494,0.078374,-0.094767,-0.087820,-0.176552,0.149058,0.224980,-0.329079,0.187947,-0.189483
#,1.499199,-0.151666,2.150062,1.835209,1.904099,2.142193,-1.108657,-1.281631,2.732129,2.948512,...,0.079698,-0.464941,1.290173,0.061074,-0.257399,-0.752442,0.019620,0.132082,-0.440150,-0.476223
$,0.630779,1.138584,2.530838,0.166183,3.076835,0.542186,-0.858887,0.884039,2.754835,-0.390936,...,0.297402,-0.254304,1.426802,-0.010306,-0.657113,-0.627469,0.097199,-0.183204,-0.213610,-0.170229
%,2.040906,0.173398,2.365521,-1.138491,0.034594,2.351219,-2.068765,-0.857941,0.967327,2.126300,...,-0.527834,-0.229152,-0.059828,0.299519,-0.925737,-0.175775,0.280792,0.260768,0.674299,0.673200
&,-0.362176,-1.536422,0.681592,-0.254282,-0.020795,2.549080,1.063519,1.306450,1.050382,2.485573,...,-0.431890,-0.154748,-0.647066,-0.048509,0.023910,-0.560396,0.427393,0.642400,0.882393,-0.388471
',-1.620776,2.052795,0.476201,-0.315580,0.532586,-0.451270,-1.238636,0.606207,-0.797014,0.126661,...,0.054849,-0.057004,0.090347,-0.235629,-0.785747,-0.306805,0.576140,0.273453,0.878228,0.013317
'',-1.888850,-0.329437,2.229829,-0.024572,0.612867,1.830826,-2.658098,1.066225,-0.894128,0.677597,...,-0.093398,-0.030841,-0.173364,-0.138874,-0.683034,-0.094501,0.465635,0.371119,0.759352,0.149494
'd,-2.117164,-1.338601,0.084229,0.462426,-1.943431,-0.868539,-1.988568,-1.283501,1.316628,1.031664,...,0.245045,0.218747,-0.037458,-0.123892,-0.492345,-0.260605,0.047124,-0.004179,0.792069,-0.005892
'll,-1.817729,-0.345378,0.854443,0.764095,-1.413824,-0.242263,-2.870903,1.914835,1.601110,1.654043,...,0.297578,0.113090,0.135073,-0.587226,-0.076004,0.153083,0.157968,0.446649,0.510730,0.062492
'm,0.698488,-0.773644,0.095428,1.951090,1.801322,-0.856540,-1.032917,-1.498475,0.703896,0.657627,...,0.308484,0.174957,0.140864,-0.164224,-0.266943,0.071756,0.262934,0.027962,0.889033,-0.010744

In [9]:
padding = pd.DataFrame({'<PAD>': np.zeros(shape=[1,embed_words.shape[1]])[0]}).T
embed_matrix = padding.append(embed_words)
embed_matrix.head()

,0,1,2,3,4,5,6,7,8,9,...,374,375,376,377,378,379,380,381,382,383
<PAD>,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
!,0.671140,-0.475781,1.225882,-0.533356,1.413614,2.528172,-0.030113,0.486537,3.412096,1.299003,...,0.361494,0.078374,-0.094767,-0.087820,-0.176552,0.149058,0.224980,-0.329079,0.187947,-0.189483
#,1.499199,-0.151666,2.150062,1.835209,1.904099,2.142193,-1.108657,-1.281631,2.732129,2.948512,...,0.079698,-0.464941,1.290173,0.061074,-0.257399,-0.752442,0.019620,0.132082,-0.440150,-0.476223
$,0.630779,1.138584,2.530838,0.166183,3.076835,0.542186,-0.858887,0.884039,2.754835,-0.390936,...,0.297402,-0.254304,1.426802,-0.010306,-0.657113,-0.627469,0.097199,-0.183204,-0.213610,-0.170229
%,2.040906,0.173398,2.365521,-1.138491,0.034594,2.351219,-2.068765,-0.857941,0.967327,2.126300,...,-0.527834,-0.229152,-0.059828,0.299519,-0.925737,-0.175775,0.280792,0.260768,0.674299,0.673200

In [10]:
word_index = {j:i+1 for i,j in enumerate(embed_matrix.index.tolist()[1:])}
tokenizer = Tokenizer()
tokenizer.word_index = word_index
sequences = tokenizer.texts_to_sequences(df.story)
data = pad_sequences(sequences, maxlen=MAXLEN)

In [11]:
random_matrix = np.random.randn(embed_matrix.shape[0], embed_matrix.shape[1])
random_matrix[0] = np.zeros([1, embed_matrix.shape[1]])

In [12]:
onehot = pd.get_dummies(df['class'])
target_labels = onehot.columns
target = onehot.as_matrix()
target

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 1, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [13]:
x_train = data[:TRAIN_SIZE]
x_test = data[TRAIN_SIZE:]

y_train = target[:TRAIN_SIZE]
y_test = target[TRAIN_SIZE:]

In [18]:
embedding_layer = Embedding(len(embed_matrix), len(embed_matrix.columns), weights=[embed_matrix.values],
                            input_length=MAXLEN, trainable=False)

sequence_input = Input(shape=(MAXLEN,), dtype='int32')
embedded_sequences = embedding_layer(sequence_input)

model = Sequential()

x = Conv1D(128, 5, activation='relu')(embedded_sequences)
x = MaxPooling1D(5)(x)
x = Conv1D(128, 5, activation='relu')(x)
x = MaxPooling1D(5)(x)
x = Dropout(0.2)(x)
x = Conv1D(128, 5, activation='relu')(x)
x = MaxPooling1D(35)(x)  # global max pooling
x = Flatten()(x)
x = Dense(128, activation='relu')(x)
output = Dense(target.shape[1], activation='softmax')(x)

model = Model(sequence_input, output)
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['acc'])

In [19]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
input_2 (InputLayer)         (None, 1000)              0
_________________________________________________________________
embedding_3 (Embedding)      (None, 1000, 384)         7680384
_________________________________________________________________
conv1d_4 (Conv1D)            (None, 996, 128)          245888
_________________________________________________________________
max_pooling1d_4 (MaxPooling1 (None, 199, 128)          0
_________________________________________________________________
conv1d_5 (Conv1D)            (None, 195, 128)          82048
_________________________________________________________________
max_pooling1d_5 (MaxPooling1 (None, 39, 128)           0
_________________________________________________________________
dropout_2 (Dropout)          (None, 39, 128)           0
_________________________________________________________________
conv1d_6 (Conv1D)            (None, 35, 128)           82048
_________________________________________________________________
max_pooling1d_6 (MaxPooling1 (None, 1, 128)            0
_________________________________________________________________
flatten_2 (Flatten)          (None, 128)               0
_________________________________________________________________
dense_3 (Dense)              (None, 128)               16512
_________________________________________________________________
dense_4 (Dense)              (None, 32)                4128
=================================================================
Total params: 8,111,008
Trainable params: 430,624
Non-trainable params: 7,680,384
_________________________________________________________________

In [20]:
model.fit(x_train, y_train, validation_data=(x_test, y_test), epochs=5, batch_size=128)

Train on 10000 samples, validate on 2509 samples
Epoch 1/2
10000/10000 [==============================] - 326s - loss: 3.2542 - acc: 0.0629 - val_loss: 3.1908 - val_acc: 0.0877
Epoch 2/2
10000/10000 [==============================] - 321s - loss: 3.1118 - acc: 0.1122 - val_loss: 2.9566 - val_acc: 0.1829

In [21]:
model.fit(x_train, y_train, validation_data=(x_test, y_test), epochs=5, batch_size=128)

Train on 10000 samples, validate on 2509 samples
Epoch 1/3
10000/10000 [==============================] - 322s - loss: 2.8345 - acc: 0.1905 - val_loss: 2.7554 - val_acc: 0.2419
Epoch 2/3
10000/10000 [==============================] - 322s - loss: 2.6604 - acc: 0.2482 - val_loss: 2.5685 - val_acc: 0.2798
Epoch 3/3
10000/10000 [==============================] - 320s - loss: 2.4569 - acc: 0.3026 - val_loss: 2.4439 - val_acc: 0.3037

In [22]:
model.fit(x_train, y_train, validation_data=(x_test, y_test), epochs=5, batch_size=128)

Train on 10000 samples, validate on 2509 samples
Epoch 1/5
10000/10000 [==============================] - 333s - loss: 2.2333 - acc: 0.3560 - val_loss: 2.2386 - val_acc: 0.3603
Epoch 2/5
10000/10000 [==============================] - 370s - loss: 2.0182 - acc: 0.4167 - val_loss: 2.0140 - val_acc: 0.4360
Epoch 3/5
10000/10000 [==============================] - 343s - loss: 1.8307 - acc: 0.4787 - val_loss: 1.9291 - val_acc: 0.4699
Epoch 4/5
10000/10000 [==============================] - 353s - loss: 1.6670 - acc: 0.5225 - val_loss: 1.8306 - val_acc: 0.5078
Epoch 5/5
10000/10000 [==============================] - 362s - loss: 1.5658 - acc: 0.5454 - val_loss: 1.8377 - val_acc: 0.5042

In [23]:
predictions = model.predict(x_test)

In [24]:
pred_values = [np.argmax(i) for i in predictions]
test_values = [np.argmax(i) for i in y_test]

In [25]:
result = pd.DataFrame({'test_values': test_values , 'pred_values': pred_values})

In [26]:
for i in range(y_test.shape[1]):
    total = result[result.test_values == i]
    correct = total[total.pred_values == i]
    print('Target -->', i)
    print('Total:', len(total))
    print('Correct', len(correct))
    print('Accuracy:', len(correct)/len(total))
    print()

Target --> 0
Total: 113
Correct 78
Accuracy: 0.6902654867256637

Target --> 1
Total: 164
Correct 99
Accuracy: 0.6036585365853658

Target --> 2
Total: 145
Correct 71
Accuracy: 0.4896551724137931

Target --> 3
Total: 99
Correct 67
Accuracy: 0.6767676767676768

Target --> 4
Total: 155
Correct 86
Accuracy: 0.5548387096774193

Target --> 5
Total: 38
Correct 8
Accuracy: 0.21052631578947367

Target --> 6
Total: 58
Correct 21
Accuracy: 0.3620689655172414

Target --> 7
Total: 71
Correct 27
Accuracy: 0.38028169014084506

Target --> 8
Total: 107
Correct 60
Accuracy: 0.5607476635514018

Target --> 9
Total: 184
Correct 139
Accuracy: 0.7554347826086957

Target --> 10
Total: 169
Correct 120
Accuracy: 0.7100591715976331

Target --> 11
Total: 4
Correct 0
Accuracy: 0.0

Target --> 12
Total: 51
Correct 0
Accuracy: 0.0

Target --> 13
Total: 10
Correct 0
Accuracy: 0.0

Target --> 14
Total: 28
Correct 0
Accuracy: 0.0

Target --> 15
Total: 40
Correct 0
Accuracy: 0.0

Target --> 16
Total: 156
Correct 76
Accuracy: 0.48717948717948717

Target --> 17
Total: 53
Correct 35
Accuracy: 0.660377358490566

Target --> 18
Total: 126
Correct 56
Accuracy: 0.4444444444444444

Target --> 19
Total: 45
Correct 6
Accuracy: 0.13333333333333333

Target --> 20
Total: 122
Correct 16
Accuracy: 0.13114754098360656

Target --> 21
Total: 15
Correct 0
Accuracy: 0.0

Target --> 22
Total: 16
Correct 0
Accuracy: 0.0

Target --> 23
Total: 70
Correct 30
Accuracy: 0.42857142857142855

Target --> 24
Total: 25
Correct 11
Accuracy: 0.44

Target --> 25
Total: 1
Correct 0
Accuracy: 0.0

Target --> 26
Total: 159
Correct 120
Accuracy: 0.7547169811320755

Target --> 27
Total: 107
Correct 67
Accuracy: 0.6261682242990654

Target --> 28
Total: 43
Correct 17
Accuracy: 0.3953488372093023

Target --> 29
Total: 23
Correct 0
Accuracy: 0.0

Target --> 30
Total: 27
Correct 0
Accuracy: 0.0

Target --> 31
Total: 85
Correct 55
Accuracy: 0.6470588235294118

In [27]:
len(result[result.test_values == result.pred_values])/len(result)

0.5041849342367477